<?php

namespace ContainerWzIapRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S5x0jv8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.S5x0jv8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.S5x0jv8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'advert' => ['privates', '.errored..service_locator.S5x0jv8.App\\Entity\\Advert', NULL, 'Cannot autowire service ".service_locator.S5x0jv8": it references class "App\\Entity\\Advert" but no such service exists.'],
        ], [
            'advert' => 'App\\Entity\\Advert',
        ]);
    }
}
