<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWzIapRr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWzIapRr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWzIapRr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWzIapRr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWzIapRr\App_KernelDevDebugContainer([
    'container.build_hash' => 'WzIapRr',
    'container.build_id' => 'ec361e0b',
    'container.build_time' => 1605757269,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWzIapRr');
